export {default as MascotsPanel} from './panel/mascotsPanel'
export {default as TemplatesPanel} from './panel/templatesPanel'
export {default as SidePanel} from './panel/sidePanel'
export {default as MainLayout} from './mainLayout/mainLayout'
export {default as Header} from './header/header'